# Cloud Workflow — daily orchestration of claw-teammate workers.
# Triggered once per day by Cloud Scheduler.
#
# Schedule logic:
#   inbox_triage   → every day
#   content_drafter → every day (social); the worker itself checks for Monday to add newsletter
#   github_gardener → Sundays only
main:
  params: [args]
  steps:
    - init:
        assign:
          - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: "us-central1"
          # day_name will be "Sunday", "Monday", etc.
          - day_name: ${text.substring(time.format(sys.now(), "EEEE"), 0, 10)}

    - run_inbox_triage:
        call: googleapis.run.v2.projects.locations.jobs.run
        args:
          name: ${"projects/" + project + "/locations/" + region + "/jobs/inbox-triage"}
        result: inbox_result

    - run_content_drafter:
        call: googleapis.run.v2.projects.locations.jobs.run
        args:
          name: ${"projects/" + project + "/locations/" + region + "/jobs/content-drafter"}
        result: content_result

    - check_sunday:
        switch:
          - condition: ${day_name == "Sunday"}
            next: run_github_gardener
        next: done

    - run_github_gardener:
        call: googleapis.run.v2.projects.locations.jobs.run
        args:
          name: ${"projects/" + project + "/locations/" + region + "/jobs/github-gardener"}
        result: github_result

    - done:
        return:
          inbox: "completed"
          content: "completed"
          github: ${if(day_name == "Sunday", "completed", "skipped (not Sunday)")}
