import type { SkillMeta } from "./types";

export const SKILL_REGISTRY: SkillMeta[] = [
  {
    id: "daily-briefing",
    name: "Daily Briefing",
    description: "Morning news briefing across tech, health IT, Africa, and fintech",
    cron: "0 13 * * *",
    cronDescription: "Daily at 1:00 PM UTC",
    requiredPlugins: [],
  },
  {
    id: "content-engine",
    name: "Content Engine",
    description: "Weekly content calendar generation from trending topics",
    cron: "0 1 * * 1",
    cronDescription: "Mondays at 1:00 AM UTC",
    requiredPlugins: ["convex-knowledge"],
  },
  {
    id: "daily-posts",
    name: "Daily Posts",
    description: "Draft daily social media posts from content calendar",
    cron: "0 13 * * *",
    cronDescription: "Daily at 1:00 PM UTC",
    requiredPlugins: ["postiz", "convex-knowledge"],
  },
  {
    id: "newsletter-writer",
    name: "Newsletter Writer",
    description: "Weekly newsletter draft from content calendar and engagement data",
    cron: "0 14 * * 2",
    cronDescription: "Tuesdays at 2:00 PM UTC",
    requiredPlugins: ["beehiiv", "convex-knowledge"],
  },
  {
    id: "engagement-monitor",
    name: "Engagement Monitor",
    description: "Weekly social media analytics and performance insights",
    cron: "0 18 * * 5",
    cronDescription: "Fridays at 6:00 PM UTC",
    requiredPlugins: ["postiz", "convex-knowledge"],
  },
  {
    id: "job-hunter",
    name: "Job Hunter",
    description: "On-demand job search, company research, and outreach drafting",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "dynoclux",
    name: "DynoClux Privacy Enforcement",
    description:
      "Scan inbox, unsubscribe, track CAN-SPAM/CCPA deadlines, detect violations, and draft compliance notices",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["dynoclux"],
  },
  {
    id: "dynosist",
    name: "DynoSist Email Assistant",
    description: "Compose Gmail drafts with file attachments via conversational interface",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["dynosist"],
  },
  {
    id: "growth-hacker",
    name: "Growth Hacker",
    description:
      "Multi-product growth strategy, experiments, and competitive analysis",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["postiz", "convex-knowledge"],
  },
  {
    id: "product-update",
    name: "Product Update",
    description:
      "Log product milestones and updates to the shared knowledge DB",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["convex-knowledge"],
  },
  {
    id: "agentmail",
    name: "AgentMail",
    description:
      "Send, receive, and manage emails through a dedicated AgentMail inbox",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["agentmail"],
  },
  {
    id: "agent-browser",
    name: "Agent Browser",
    description:
      "Browser automation for navigating pages, filling forms, clicking buttons, taking screenshots, and extracting data from websites",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "comic-brief",
    name: "Comic Brief",
    description:
      "Generate copy-paste-ready Gemini prompts for branded comic-style illustrations",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "crm-pipeline",
    name: "CRM Pipeline",
    description:
      "Manage CRM contacts, deals, companies, and sales pipeline across HubSpot or Zoho",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "metric-health-echo",
    name: "MetricHealth Echo",
    description:
      "Healthcare tech thought leadership posts for LinkedIn and X, focused on Metric Health and brain health",
    cron: "0 */4 * * *",
    cronDescription: "Every 4 hours",
    requiredPlugins: ["postiz"],
  },
  {
    id: "agency-sales-pack",
    name: "Sales Division (8 agents)",
    description:
      "Outbound strategist, discovery coach, deal strategist, sales engineer, proposal strategist, pipeline analyst, account strategist, and sales coach",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
    bundledSkills: [
      "sales-outbound-strategist",
      "sales-discovery-coach",
      "sales-deal-strategist",
      "sales-engineer",
      "sales-proposal-strategist",
      "sales-pipeline-analyst",
      "sales-account-strategist",
      "sales-coach",
    ],
  },
  {
    id: "agency-marketing-pack",
    name: "Marketing Division (8 agents)",
    description:
      "Content creator, LinkedIn strategist, social media manager, SEO, growth hacker, podcast strategist, and more",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
    bundledSkills: [
      "marketing-content-creator",
      "marketing-linkedin-content-creator",
      "marketing-social-media-strategist",
      "marketing-growth-hacker",
      "marketing-seo-specialist",
      "marketing-podcast-strategist",
      "marketing-book-co-author",
      "marketing-carousel-growth-engine",
    ],
  },
  {
    id: "agency-engineering-pack",
    name: "Engineering Division (23 agents)",
    description:
      "Frontend developer, backend architect, AI engineer, DevOps automator, security engineer, and 18 more engineering-focused agents",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
    bundledSkills: [
      "engineering-frontend-developer",
      "engineering-backend-architect",
      "engineering-mobile-app-builder",
      "engineering-ai-engineer",
      "engineering-devops-automator",
      "engineering-rapid-prototyper",
      "engineering-senior-developer",
      "engineering-security-engineer",
      "engineering-autonomous-optimization-architect",
      "engineering-embedded-firmware-engineer",
      "engineering-incident-response-commander",
      "engineering-solidity-smart-contract-engineer",
      "engineering-technical-writer",
      "engineering-threat-detection-engineer",
      "engineering-wechat-mini-program-developer",
      "engineering-code-reviewer",
      "engineering-database-optimizer",
      "engineering-git-workflow-master",
      "engineering-software-architect",
      "engineering-sre",
      "engineering-ai-data-remediation-engineer",
      "engineering-data-engineer",
      "engineering-feishu-integration-developer",
    ],
  },
  {
    id: "job-scout",
    name: "Job Scout",
    description: "Full pipeline — find jobs, research companies, map contacts, draft outreach",
    cron: "0 14 * * 1",
    cronDescription: "Mondays at 2:00 PM UTC",
    requiredPlugins: ["job-search"],
  },
  {
    id: "company-intel",
    name: "Company Intel",
    description: "Deep research on a target company and save to job search dashboard",
    cron: null,
    cronDescription: "",
    requiredPlugins: ["job-search"],
  },
  {
    id: "network-scan",
    name: "Network Scan",
    description: "Find contacts at a target company and draft outreach messages",
    cron: null,
    cronDescription: "",
    requiredPlugins: ["job-search"],
  },
];

export function getSkillById(id: string): SkillMeta | undefined {
  return SKILL_REGISTRY.find((s) => s.id === id);
}
