import type { SkillMeta } from "./types";

export const SKILL_REGISTRY: SkillMeta[] = [
  {
    id: "daily-briefing",
    name: "Daily Briefing",
    description: "Morning news briefing across tech, health IT, Africa, and fintech",
    cron: "0 13 * * *",
    cronDescription: "Daily at 1:00 PM UTC",
    requiredPlugins: [],
  },
  {
    id: "content-engine",
    name: "Content Engine",
    description: "Weekly content calendar generation from trending topics",
    cron: "0 1 * * 1",
    cronDescription: "Mondays at 1:00 AM UTC",
    requiredPlugins: ["convex-knowledge"],
  },
  {
    id: "daily-posts",
    name: "Daily Posts",
    description: "Draft daily social media posts from content calendar",
    cron: "0 13 * * *",
    cronDescription: "Daily at 1:00 PM UTC",
    requiredPlugins: ["postiz", "convex-knowledge"],
  },
  {
    id: "newsletter-writer",
    name: "Newsletter Writer",
    description: "Weekly newsletter draft from content calendar and engagement data",
    cron: "0 14 * * 2",
    cronDescription: "Tuesdays at 2:00 PM UTC",
    requiredPlugins: ["beehiiv", "convex-knowledge"],
  },
  {
    id: "engagement-monitor",
    name: "Engagement Monitor",
    description: "Weekly social media analytics and performance insights",
    cron: "0 18 * * 5",
    cronDescription: "Fridays at 6:00 PM UTC",
    requiredPlugins: ["postiz", "convex-knowledge"],
  },
  {
    id: "job-hunter",
    name: "Job Hunter",
    description: "On-demand job search, company research, and outreach drafting",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "dynoclux",
    name: "DynoClux Privacy Enforcement",
    description:
      "Scan inbox, unsubscribe, track CAN-SPAM/CCPA deadlines, detect violations, and draft compliance notices",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["dynoclux"],
  },
  {
    id: "dynosist",
    name: "DynoSist Email Assistant",
    description: "Compose Gmail drafts with file attachments via conversational interface",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["dynosist"],
  },
  {
    id: "growth-hacker",
    name: "Growth Hacker",
    description:
      "Multi-product growth strategy, experiments, and competitive analysis",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["postiz", "convex-knowledge"],
  },
  {
    id: "product-update",
    name: "Product Update",
    description:
      "Log product milestones and updates to the shared knowledge DB",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["convex-knowledge"],
  },
  {
    id: "agentmail",
    name: "AgentMail",
    description:
      "Send, receive, and manage emails through a dedicated AgentMail inbox",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: ["agentmail"],
  },
  {
    id: "agent-browser",
    name: "Agent Browser",
    description:
      "Browser automation for navigating pages, filling forms, clicking buttons, taking screenshots, and extracting data from websites",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "comic-brief",
    name: "Comic Brief",
    description:
      "Generate copy-paste-ready Gemini prompts for branded comic-style illustrations",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "crm-pipeline",
    name: "CRM Pipeline",
    description:
      "Manage CRM contacts, deals, companies, and sales pipeline across HubSpot or Zoho",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
  },
  {
    id: "metric-health-echo",
    name: "MetricHealth Echo",
    description:
      "Healthcare tech thought leadership posts for LinkedIn and X, focused on Metric Health and brain health",
    cron: "0 */4 * * *",
    cronDescription: "Every 4 hours",
    requiredPlugins: ["postiz"],
  },
  {
    id: "agency-sales-pack",
    name: "Sales Division (8 agents)",
    description:
      "Outbound strategist, discovery coach, deal strategist, sales engineer, proposal strategist, pipeline analyst, account strategist, and sales coach",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
    bundledSkills: [
      "sales-outbound-strategist",
      "sales-discovery-coach",
      "sales-deal-strategist",
      "sales-engineer",
      "sales-proposal-strategist",
      "sales-pipeline-analyst",
      "sales-account-strategist",
      "sales-coach",
    ],
  },
  {
    id: "agency-marketing-pack",
    name: "Marketing Division (26 agents)",
    description:
      "Growth hacker, content creator, SEO specialist, social media strategist, and 22 more marketing-focused agents",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
    bundledSkills: [
      "marketing-growth-hacker",
      "marketing-content-creator",
      "marketing-twitter-engager",
      "marketing-tiktok-strategist",
      "marketing-instagram-curator",
      "marketing-reddit-community-builder",
      "marketing-app-store-optimizer",
      "marketing-social-media-strategist",
      "marketing-xiaohongshu-specialist",
      "marketing-wechat-official-account",
      "marketing-zhihu-strategist",
      "marketing-baidu-seo-specialist",
      "marketing-bilibili-content-strategist",
      "marketing-carousel-growth-engine",
      "marketing-linkedin-content-creator",
      "marketing-china-ecommerce-operator",
      "marketing-kuaishou-strategist",
      "marketing-seo-specialist",
      "marketing-book-co-author",
      "marketing-cross-border-ecommerce",
      "marketing-douyin-strategist",
      "marketing-livestream-commerce-coach",
      "marketing-podcast-strategist",
      "marketing-private-domain-operator",
      "marketing-short-video-editing-coach",
      "marketing-weibo-strategist",
    ],
  },
  {
    id: "agency-engineering-pack",
    name: "Engineering Division (23 agents)",
    description:
      "Frontend developer, backend architect, AI engineer, DevOps automator, security engineer, and 18 more engineering-focused agents",
    cron: null,
    cronDescription: "On-demand only",
    requiredPlugins: [],
    bundledSkills: [
      "engineering-frontend-developer",
      "engineering-backend-architect",
      "engineering-mobile-app-builder",
      "engineering-ai-engineer",
      "engineering-devops-automator",
      "engineering-rapid-prototyper",
      "engineering-senior-developer",
      "engineering-security-engineer",
      "engineering-autonomous-optimization-architect",
      "engineering-embedded-firmware-engineer",
      "engineering-incident-response-commander",
      "engineering-solidity-smart-contract-engineer",
      "engineering-technical-writer",
      "engineering-threat-detection-engineer",
      "engineering-wechat-mini-program-developer",
      "engineering-code-reviewer",
      "engineering-database-optimizer",
      "engineering-git-workflow-master",
      "engineering-software-architect",
      "engineering-sre",
      "engineering-ai-data-remediation-engineer",
      "engineering-data-engineer",
      "engineering-feishu-integration-developer",
    ],
  },
];

export function getSkillById(id: string): SkillMeta | undefined {
  return SKILL_REGISTRY.find((s) => s.id === id);
}
