export const CATALYST_SLIDES = [
  {
    webinarId: "catalyst-mar-2026",
    order: 1,
    type: "cover" as const,
    title: "Practical AI for Small Business",
    subtitle: "How to Save Time, Grow Revenue, and Compete Globally",
    presenterInfo: {
      name: "Adebayo Dawodu",
      title: "Digital Transformation Tech Consultant",
      subtitle: undefined,
      event: "Change Catalyst Co — March 2026",
    },
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Good evening everyone! My name is Adebayo Dawodu — I'm a technology leader and digital transformation consultant. Today I'm going to show you, hands-on, how to use AI to save time and money in your business. No theory. No hype. We're going to build real things together.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 2,
    type: "content" as const,
    title: "The Reality for Small Businesses Today",
    bullets: [
      "You wear every hat — CEO, marketer, customer support, accountant",
      "Hiring help is expensive: a VA costs $300–800/month",
      "Your competitors with bigger teams are moving faster",
      "You're spending hours on tasks that AI can do in minutes",
    ],
    highlightBox: "The gap isn't talent — it's leverage. AI is the great equalizer for small businesses.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Quick show of hands — how many of you are the marketing department, the customer service team, AND the CEO of your business? Yeah, that's most of us. The challenge isn't that you're not talented enough — it's that there aren't enough hours in the day.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 3,
    type: "content" as const,
    title: "What AI Can Actually Do for You Today",
    subtitle: "Forget the hype. Here's what's practical right now, for free or nearly free:",
    twoColumns: {
      left: { heading: "Save You Time", items: ["Draft and sort your emails", "Auto-reply on WhatsApp", "Schedule social media posts", "Summarize long documents"] },
      right: { heading: "Make You Money", items: ["Create digital products (eBooks, guides)", "Build a website or landing page", "Generate marketing content", "Design logos and visuals"] },
    },
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Let's be specific. I'm not talking about robots or sci-fi. I'm talking about typing a message and getting back work that would normally take you hours.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 4,
    type: "content" as const,
    title: "What You're Really Spending",
    tableHeaders: ["Task", "Manual Cost", "With AI", ""],
    tableRows: [
      { cells: ["Social media management", "$200–500/mo or 8hrs/week", "30 min/week", "Save 90%"] },
      { cells: ["Email management", "2 hrs/day", "20 min/day", "Save 80%"] },
      { cells: ["Website (basic)", "$500–2,000 one-time", "$0 (free tools)", "Save 100%"] },
      { cells: ["Digital product creation", "$300–1,000 to outsource", "$0 + your expertise", "New revenue"] },
      { cells: ["Customer support replies", "3 hrs/day", "30 min/day", "Save 85%"] },
    ],
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Let me put numbers to this. The average small business owner I work with saves 15-20 hours per week after setting up basic AI workflows. That's like hiring a part-time employee for free.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 5,
    type: "content" as const,
    title: "Your AI Toolkit (All Free to Start)",
    bullets: [
      "ChatGPT / Claude / Gemini — Your AI brain for writing, planning, creating",
      "Canva — Design anything: posts, eBooks, presentations, logos",
      "WhatsApp Business — Auto-replies, catalogs, quick responses",
      "Buffer / Later — Schedule social media posts for free",
      "Bolt.new / Framer — Build a website by describing what you want",
      "Gamma.app — Create presentations from a single prompt",
    ],
    highlightBox: "You don't need to be technical. If you can type a message, you can use AI.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Here's the good news — every tool I'm showing you today has a free version. You don't need to spend a single naira to get started.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 6,
    type: "section" as const,
    title: "Let's Talk About YOU",
    subtitle: "Before I show you how — I want to know what you need",
    showInPublic: false,
    showDynoclawCta: false,
    speakerNotes: "This is the most important section. It determines which demos you emphasize. Listen for patterns.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 7,
    type: "interactive" as const,
    title: "What Kind of Business Do You Run?",
    instruction: "I'll tailor the demos to what's most useful for the room.",
    options: [
      "🛍️ Product / E-commerce",
      "💼 Services / Consulting",
      "📚 Content / Education",
      "🏗️ Trades / Local Business",
      "💡 I have an idea, not started yet",
    ],
    showInPublic: false,
    showDynoclawCta: false,
    speakerNotes: "Before I jump into demos, I need to know who's in the room. Drop in the chat or just shout it out — what kind of business do you run? Listen for patterns. If mostly e-commerce, emphasize social media + digital products. If services, emphasize email + WhatsApp + website.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 8,
    type: "interactive" as const,
    title: "What Takes the Most Time in Your Day?",
    instruction: "This tells me which demos to spend the most time on.",
    options: [
      "📧 Managing emails & messages",
      "📱 Creating social media content",
      "🤝 Responding to customers",
      "🎨 Design work (graphics, logos)",
      "🌐 I don't have a website yet",
      "📦 I want to create a digital product",
    ],
    showInPublic: false,
    showDynoclawCta: false,
    speakerNotes: "Now the real question — what takes the most time? Tally mentally. This tells you which demo to spend the most time on. If 60% say social media, spend 12 minutes on Demo 3 and 5 minutes on Demo 1.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 9,
    type: "interactive" as const,
    title: "How Familiar Are You with AI Tools?",
    instruction: "This helps me set the right pace for the demos.",
    options: [
      "🆕 Never used AI before",
      "👀 I've tried ChatGPT once or twice",
      "⚡ I use it sometimes but want to do more",
      "🚀 I use it daily and want advanced tips",
    ],
    showInPublic: false,
    showDynoclawCta: false,
    speakerNotes: "If mostly beginners, slow down, explain what ChatGPT is. If mixed, address beginners first then move to power tips. If advanced, skip basics, focus on chaining prompts.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 10,
    type: "section" as const,
    title: "Live Demos",
    subtitle: "Let's build something real — together, right now",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "USE AUDIENCE BUSINESSES for all demos. Ask 'Who here sells food? Fashion? Let's do yours.' They'll screenshot it and share it.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 11,
    type: "demo" as const,
    title: "Demo 1: Tame Your Inbox in 5 Minutes",
    demoSteps: [
      "Open ChatGPT or Claude (free version)",
      "Paste an actual business email you received (or use the sample)",
      "Prompt: \"Read this email. Draft a professional reply that [accepts/declines/asks for more info]. Keep it under 4 sentences.\"",
      "Show the reply — edit one line — send",
      "Prompt: \"Now create 3 email templates I can reuse: inquiry response, payment follow-up, and meeting confirmation.\"",
    ],
    demoSpeakerNote: "Use a real email from your inbox (redacted). The audience connects more when it's real, not hypothetical. Save the templates to a Google Doc and share the link.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Key line: 'How long would that have taken you? 15 minutes? It just took 15 seconds.'",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 12,
    type: "demo" as const,
    title: "Demo 2: WhatsApp Auto-Replies That Sound Like You",
    demoSteps: [
      "Open WhatsApp Business → Settings → Business Tools → Quick Replies",
      "Prompt ChatGPT: \"I run a [business type]. Create 5 WhatsApp quick replies for: greeting, pricing question, availability, payment info, thank you after purchase.\"",
      "Copy each reply into WhatsApp Business quick replies",
      "Show how to trigger them: type \"/\" in any chat",
      "Set up an Away Message for after-hours with AI-generated text",
    ],
    demoSpeakerNote: "Ask someone in the audience for their business type. Generate replies for THEIR business live. This makes it personal and memorable.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Key line: 'You now have a 24/7 auto-responder. Your customers get answers even when you're asleep.'",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 13,
    type: "demo" as const,
    title: "Demo 3: One Week of Social Media in 10 Minutes",
    demoSteps: [
      "Prompt: \"I run a [business]. Create a 5-day social media calendar for Instagram/LinkedIn. Each day: a caption, 3 hashtags, and a content type (tip, story, testimonial, promo, question).\"",
      "Show the output — a full week planned in 30 seconds",
      "Pick one post → Prompt: \"Now write the full Instagram caption for Day 1. Make it engaging, end with a call to action.\"",
      "Open Canva → search a template → paste the caption → done",
      "Open Buffer (free) → schedule the post",
    ],
    demoSpeakerNote: "Use an audience member's actual business. 'Who sells food? Fashion? Let's do yours.' Generate their real content live. They'll screenshot it.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "This is usually the biggest crowd-pleaser. Key line: 'You just planned a whole week of content in the time it takes to drink your coffee.'",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 14,
    type: "demo" as const,
    title: "Demo 4: Create a Digital Product in 15 Minutes",
    demoSteps: [
      "Ask the audience: \"What do people always ask you for advice about?\"",
      "Take one answer. Prompt: \"Create a 10-page eBook outline on [topic]. Include a catchy title, chapter titles, and 3 bullet points per chapter.\"",
      "Prompt: \"Now write the full content for Chapter 1.\"",
      "Open Canva → eBook template → paste content → style it",
      "Show how to sell it: Gumroad (free), Selar.co (popular in Africa), or link from your WhatsApp status",
    ],
    demoSpeakerNote: "This is the 'aha moment' for most people. They realize they can package their knowledge and sell it today. Emphasize: 'If people ask you for advice, you have a product.'",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Key line: 'You just created something you can sell for $5-20. If 100 people buy it, that's $500-2,000 from knowledge you already have.' Mention Selar.co — they'll relate.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 15,
    type: "demo" as const,
    title: "Demo 5: Build a Website Without Writing Code",
    demoSteps: [
      "Open bolt.new (free, no sign-up needed)",
      "Prompt: \"Build a landing page for a [business type] based in Lagos. Include: hero section, services list, testimonials, WhatsApp contact button, pricing section.\"",
      "Watch it generate a full website in real-time",
      "Make a change: \"Change the color scheme to green and gold. Add a 'Book a Consultation' button.\"",
      "Deploy it — live on the internet in under 2 minutes",
    ],
    demoSpeakerNote: "This is the jaw-dropper. Time it. 'We just built a website in under 3 minutes that would have cost you $500-2000.' Use an audience member's business for maximum impact.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Save this for last among demos — it gets the strongest reaction.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 16,
    type: "content" as const,
    title: "The Secret: Good Prompts = Good Results",
    subtitle: "The \"Context + Task + Format\" Formula",
    bullets: [
      "Context: \"I run a catering business in Abuja...\"",
      "Task: \"Write an Instagram caption promoting my weekend packages...\"",
      "Format: \"Keep it under 150 words, use emojis, end with a CTA\"",
    ],
    highlightBox: "Bad prompt: \"Write me a post\"\n\nGood prompt: \"I run a catering business in Abuja that specializes in small chops for parties. Write an engaging Instagram caption promoting our new weekend party package (50 guests, ₦150K). Use a fun, warm tone. Include emojis and end with 'DM us to book.'\"",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Read the bad prompt, then the good prompt. The contrast makes the lesson stick.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 17,
    type: "interactive" as const,
    title: "Your Turn! Write a Prompt Right Now",
    instruction: "Take 2 minutes. Then share what you got — best one wins bragging rights! 🏆",
    options: [
      "I run a [your business] in [your city].\nCreate a WhatsApp status update that promotes [your product/service].\nKeep it under 3 lines. Make it sound natural, not salesy.\nInclude a price and end with 'Send 📩 to order.'",
    ],
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Walk around (if in person) or watch the chat. Pick 2-3 good ones to read aloud. '[Name], read yours! That's great — see how specific it is?'",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 18,
    type: "content" as const,
    title: "Power User Tips",
    bullets: [
      "Save your best prompts. Keep a Google Doc of prompts that work. Reuse them weekly.",
      "Give AI your brand voice. Tell it: \"Write like me — casual, confident, Nigerian English is fine.\"",
      "Chain prompts. Use the output of one prompt as input for the next. \"Now turn that blog post into 5 tweets.\"",
      "Use AI for research first. \"What are the top 10 questions people ask about [my industry]?\" — then create content answering each one.",
      "Batch your work. Generate a whole month of content in one sitting. Schedule it. Forget it.",
    ],
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Keep these quick. Don't lecture — rapid-fire.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 19,
    type: "content" as const,
    title: "Mistakes to Avoid",
    bullets: [
      "Copy-pasting without editing. AI gives you 80% — you add the 20% that makes it yours",
      "Using AI for everything. It's a tool, not a replacement for your expertise and relationships",
      "Ignoring your unique voice. Your customers follow YOU. Keep your personality in the content",
      "Overthinking it. Start messy. Improve later. The worst AI content is the content you never created",
      "Paying before trying free. Most AI tools have free tiers that are more than enough to start",
    ],
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Keep these quick. Don't lecture — rapid-fire.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 20,
    type: "content" as const,
    title: "Your AI Action Plan — This Week",
    tableHeaders: ["Day", "Action", "Time"],
    tableRows: [
      { cells: ["Today", "Set up WhatsApp Business quick replies (5 templates)", "15 min"] },
      { cells: ["Tomorrow", "Generate a week of social media content + schedule it", "20 min"] },
      { cells: ["Day 3", "Create 3 reusable email templates for common requests", "10 min"] },
      { cells: ["Day 4", "Outline your first digital product (eBook or guide)", "15 min"] },
      { cells: ["Day 5", "Build a landing page or update your business bio", "20 min"] },
    ],
    highlightBox: "Total time investment: ~80 minutes across 5 days. That's it. You'll save 10x that every month going forward.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "I don't want you to leave here inspired and then do nothing. Here's your homework — 15 minutes a day for 5 days.",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 21,
    type: "cover" as const,
    title: "AI Won't Replace You.",
    subtitle: "But a business owner using AI will outpace one who isn't.",
    highlightBox: "Start small. Start today. Start with one prompt.",
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Let this slide breathe. Pause before speaking. 'AI won't replace you. Your relationships, your expertise, your hustle — that's yours. But the business owner who uses AI as a tool will move faster than the one who doesn't.'",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 22,
    type: "cover" as const,
    title: "Questions?",
    subtitle: "Let's talk about YOUR business",
    presenterInfo: {
      name: "Adebayo Dawodu",
      title: "Technology Leader — Metric Health & ParallelScore",
      subtitle: "Digital Transformation Tech Consultant",
      event: "Change Catalyst Co — Practical AI for Small Business — March 2026",
    },
    showInPublic: true,
    showDynoclawCta: false,
    speakerNotes: "Common questions: 'Is AI safe?' — Your prompts are not used to train the model on paid plans. 'Which AI is best?' — They all work well, pick one and learn it. 'Can AI do [specific thing]?' — Try it right now.",
  },
  // DynoClaw CTA slides (only shown in public /slides version)
  {
    webinarId: "catalyst-mar-2026",
    order: 23,
    type: "section" as const,
    title: "What If You Didn't Have to Do Any of This Manually?",
    subtitle: "Everything you just learned — automated, running 24/7",
    showInPublic: true,
    showDynoclawCta: true,
    speakerNotes: "",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 24,
    type: "content" as const,
    title: "Meet DynoClaw",
    subtitle: "Your AI-powered business teammate that runs while you sleep",
    bullets: [
      "Daily briefings delivered to your Telegram — news, trends, opportunities",
      "Auto-generated social media content — posts, carousels, comics",
      "Email management — drafts, follow-ups, privacy enforcement",
      "Digital product creation — from idea to published, hands-free",
      "Newsletter writing — research, draft, and schedule automatically",
      "All your tools connected — WhatsApp, Gmail, social media, CRM",
    ],
    highlightBox: "Everything we demoed today? DynoClaw does it automatically, every day, without you lifting a finger.",
    showInPublic: true,
    showDynoclawCta: true,
    speakerNotes: "",
  },
  {
    webinarId: "catalyst-mar-2026",
    order: 25,
    type: "cta" as const,
    title: "Ready to Automate Your Business?",
    subtitle: "Tell us about your business and we'll show you what we can automate",
    ctaButton: {
      label: "Get Started with DynoClaw",
      url: "https://www.dynoclaw.com",
    },
    showInPublic: true,
    showDynoclawCta: true,
    speakerNotes: "",
  },
];
